import random
from models.schemas_clean import CleanRequest, CleanResponse, CleanItem

class CleanService:
    @staticmethod
    def analyze_storage(request: CleanRequest) -> CleanResponse:
        """
        Simulates identifying cleanable items based on heuristic baselines 
        such as total apps installed and available storage.
        """
        items = []
        total_cleanable = 0

        # Heuristic 1: App Cache (Safe to clean)
        # Average cache per app: 5MB - 35MB
        avg_cache_per_app = random.randint(5 * 1024 * 1024, 35 * 1024 * 1024)
        app_cache_bytes = request.installed_apps_count * avg_cache_per_app
        items.append(CleanItem(
            id="app_cache",
            category="App Cache",
            description="Cached files generated by applications to speed up performance.",
            size_bytes=app_cache_bytes,
            is_safe_to_clean=True
        ))
        total_cleanable += app_cache_bytes

        # Heuristic 2: Residual Files
        # Based on used space heuristics (approx 1-3% of used space might be residual)
        residual_bytes = int(request.used_space_bytes * random.uniform(0.01, 0.03))
        items.append(CleanItem(
            id="residual_files",
            category="Residual Files",
            description="Leftover data from uninstalled or updated apps.",
            size_bytes=residual_bytes,
            is_safe_to_clean=True
        ))
        total_cleanable += residual_bytes

        # Heuristic 3: Temporary and AD files
        temp_bytes = random.randint(100 * 1024 * 1024, 800 * 1024 * 1024) # 100MB - 800MB
        items.append(CleanItem(
            id="temp_files",
            category="Temporary Files",
            description="Logs, temporary ad data, and system crash dumps.",
            size_bytes=temp_bytes,
            is_safe_to_clean=True
        ))
        total_cleanable += temp_bytes
        
        # Heuristic 4: Obsolete APKs
        apk_bytes = random.choice([0, 0, 150 * 1024 * 1024, 500 * 1024 * 1024, 1.2 * 1024 * 1024 * 1024])
        if apk_bytes > 0:
            items.append(CleanItem(
                id="apk_files",
                category="Obsolete APKs",
                description="Installation packages that are no longer needed.",
                size_bytes=int(apk_bytes),
                is_safe_to_clean=True
            ))
            total_cleanable += int(apk_bytes)

        # Health score (100 if minimal junk, degrades as junk grows)
        junk_ratio = total_cleanable / max(request.used_space_bytes, 1)
        health_score = max(40, 100 - int(junk_ratio * 300)) # If junk is 10%, score is 70

        return CleanResponse(
            total_cleanable_bytes=total_cleanable,
            categories=items,
            storage_health_score=health_score
        )
